### PR TITLE
Attempt to fix #3

### LINKED ISSUE #3: Optional req.files for endpoints that consumes one of two types
Hello,

First, thank you for this cleary good documented module.
I have a issue with this module for an [endpoint](https://github.com/SourceCodeOER/sourcecode_api/blob/temp-master/openapi/paths/bulk.yaml#L115) that consumes either `application/json` or `multipart/form-data` ( depending of the context ).

When I tried to use the `application/json` version, I got a error because of this (`req.files` is undefined for JSON endpoint) : 

image

Could you accept my PR (that should handle all the cases) ?
With this small modification, there will be no problem for people in my situation that cannot split an endpoint in two ^^

Thanks

### PR DESCRIPTION
**Pull request by jy95**
Attempt to fix bug #3 
( only add a `if req.is('multipart') ` to solve the issue )

### CODE REVIEW

**Comment by Gi60s** [comment]
Looks great. Thanks for the issue and PR.

**Comment by jy95** [comment]
@Gi60s A pleasure to contribute ;)  If you can help me solve this [issue](https://github.com/byu-oit/openapi-enforcer-middleware/issues/21) , I can completly change my previous validator to yours

**Comment by Gi60s** [comment]
:) I was just reading through that issue. I'll have a bit of time today to see what I can figure out with that issue, after that it will be a few days before I can swing back to it.

Sorry for the slow responses during this holiday season.

**Comment by jy95** [comment]
Even if it takes time, answers are better than nothing ^^
I tried to target the problematic code in the explanation of my issue : It should help you narrow down the cause of this issue.

**Pull request merged**
